# https://github.com/SemirAman/assignment
language: node_js
node_js:
  - 10.9.0

cache: npm

env:
  - NOW_TOKEN=Tun0LzjMy9T1Y23KjzGZCw

install:
  - npm install

script:
  - npm run build
  - npm run test
  
before_install:
  - "npm config set spin false"
  - npm i -g now

deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true
